
import { type ContentItem, ContentType, ContentCategory } from './types';

export const MOCK_CONTENT: ContentItem[] = [
  {
    id: 'qa1',
    type: ContentType.Article,
    title: 'Quantum Awakening: The Science of Higher Consciousness',
    author: 'Dr. Aris Thorne',
    preview: 'Explore how quantum field theory and consciousness research reveal the science behind spiritual awakening, combining entanglement and non-dual awareness.',
    category: ContentCategory.Quantum,
    price: 79,
    isPremium: true,
    published: true,
    pdfUrl: 'quantum_awakening_science.pdf',
    createdAt: '2024-08-01T10:00:00Z',
  },
  {
    id: 'vm1',
    type: ContentType.Article,
    title: 'Vibrational Mastery: The 3-6-9 Code',
    author: 'Nikola Tesla (Interpreted by A.I.)',
    preview: 'Unlock Nikola Tesla’s 3-6-9 theory, frequency resonance, and how sound and vibration shape reality. Includes frequency maps for manifestation.',
    category: ContentCategory.Spiritual,
    price: 69,
    isPremium: true,
    published: true,
    pdfUrl: 'vibrational_mastery_369.pdf',
    createdAt: '2024-07-31T11:00:00Z',
  },
  {
    id: 'qeh1',
    type: ContentType.Research,
    title: 'Quantum Energy Healing: Science Meets Spirit',
    author: 'The Esoteric Institute',
    preview: 'A bridge between Reiki, Pranic Healing, and Quantum Biology research on energy transfer, with techniques backed by scientific studies.',
    category: ContentCategory.Research,
    price: 129,
    isPremium: true,
    published: true,
    pdfUrl: 'quantum_energy_healing.pdf',
    createdAt: '2024-07-30T14:30:00Z',
  },
  {
    id: 'hu1',
    type: ContentType.Article,
    title: 'The Holographic Universe & Consciousness',
    author: 'Dr. Evelyn Reed',
    preview: 'Delve into the holographic principle and how reality may be a cosmic projection, with references from Bohm, Pribram, and modern physics.',
    category: ContentCategory.Quantum,
    price: 59,
    isPremium: true,
    published: true,
    pdfUrl: 'holographic_universe_consciousness.pdf',
    createdAt: '2024-07-29T09:00:00Z',
  },
  {
    id: 'qm1',
    type: ContentType.Article,
    title: 'Quantum Manifestation: Collapse the Wave',
    author: 'Yash Sharma',
    preview: 'A practical workbook blending the Law of Attraction with Quantum Mechanics to teach scientific manifestation techniques.',
    category: ContentCategory.Spiritual,
    price: 89,
    isPremium: true,
    published: true,
    pdfUrl: 'quantum_manifestation_workbook.pdf',
    createdAt: '2024-07-28T18:00:00Z',
  },
  {
    id: 'tc1',
    type: ContentType.Article,
    title: 'Time & Consciousness: Quantum Time Travel',
    author: 'Dr. Kenji Tanaka',
    preview: 'Explore retrocausality, quantum time loops, and consciousness beyond linear time with meditative exercises for shifting perception.',
    category: ContentCategory.Quantum,
    price: 79,
    isPremium: true,
    published: true,
    pdfUrl: 'time_consciousness_quantum.pdf',
    createdAt: '2024-07-27T12:00:00Z',
  },
  {
    id: 'sg1',
    type: ContentType.Article,
    title: 'Sacred Geometry & Quantum Reality',
    author: 'Ananya Sharma',
    preview: 'Connect fractals, Fibonacci sequences, and quantum fields with spiritual geometry. Includes printable templates.',
    category: ContentCategory.Spiritual,
    price: 59,
    isPremium: true,
    published: true,
    pdfUrl: 'sacred_geometry_quantum.pdf',
    createdAt: '2024-07-26T11:00:00Z',
  },
  {
    id: 'de1',
    type: ContentType.Research,
    title: 'Dark Energy & the Spiritual Void',
    author: 'MIT Consciousness Lab',
    preview: 'How cosmology’s dark energy theory aligns with spiritual concepts of emptiness and void meditation, with insights from Zen and physics.',
    category: ContentCategory.Research,
    price: 99,
    isPremium: true,
    published: true,
    pdfUrl: 'dark_energy_spiritual_void.pdf',
    createdAt: '2024-07-25T09:45:00Z',
  },
  {
    id: 'qb1',
    type: ContentType.Research,
    title: 'Quantum Biology & Spiritual Evolution',
    author: 'Dr. Evelyn Reed',
    preview: 'A report on how microtubules and quantum tunneling in biology hint at cellular consciousness, linking to higher spiritual states.',
    category: ContentCategory.Quantum,
    price: 149,
    isPremium: true,
    published: true,
    pdfUrl: 'quantum_biology_evolution.pdf',
    createdAt: '2024-07-24T16:00:00Z',
  },
  {
    id: 'fh1',
    type: ContentType.Article,
    title: 'Frequency Healing Toolkit',
    author: 'The Esoteric Institute',
    preview: 'A curated set of frequencies (binaural beats, Solfeggio) with physics explanations, guided meditations, and affirmations.',
    category: ContentCategory.Spiritual,
    price: 119,
    isPremium: true,
    published: true,
    pdfUrl: 'frequency_healing_toolkit.zip',
    createdAt: '2024-07-23T15:00:00Z',
  },
  {
    id: 'q1',
    type: ContentType.Article,
    title: 'The Observer Effect in Consciousness',
    author: 'Dr. Evelyn Reed',
    preview: 'Exploring the parallels between quantum mechanics and the subjective experience of reality.',
    category: ContentCategory.Quantum,
    price: 49,
    isPremium: true,
    published: true,
    pdfUrl: 'consciousness_observer_effect.pdf',
    createdAt: '2024-05-20T10:00:00Z',
  },
  {
    id: 'q2',
    type: ContentType.Research,
    title: 'Entanglement and Non-Local Mind',
    author: 'Dr. Kenji Tanaka',
    preview: 'A meta-analysis of studies suggesting consciousness operates beyond classical neural pathways.',
    category: ContentCategory.Quantum,
    price: 99,
    isPremium: true,
    published: true,
    pdfUrl: 'non_local_mind_entanglement.pdf',
    createdAt: '2024-06-15T14:30:00Z',
  },
  {
    id: 'q3',
    type: ContentType.Quote,
    title: 'Planck\'s Wisdom',
    author: 'Max Planck',
    preview: '"I regard consciousness as fundamental. I regard matter as derivative from consciousness."',
    category: ContentCategory.Quantum,
    price: 0,
    isPremium: false,
    published: true,
    createdAt: '2024-04-01T09:00:00Z',
  },
  {
    id: 's1',
    type: ContentType.Article,
    title: 'Vedic Cosmology and Modern Physics',
    author: 'Ananya Sharma',
    preview: 'Discovering the ancient roots of holographic universe theories in Vedic texts.',
    category: ContentCategory.Spiritual,
    price: 29,
    isPremium: true,
    published: true,
    pdfUrl: 'vedic_cosmology_physics.pdf',
    createdAt: '2024-07-01T11:00:00Z',
  },
  {
    id: 's2',
    type: ContentType.Poem,
    title: 'Ode to the Void',
    author: 'A. Rumi',
    preview: 'From nothingness, all things arise. In silence, the universe speaks...',
    category: ContentCategory.Spiritual,
    price: 0,
    isPremium: false,
    published: true,
    createdAt: '2024-03-10T18:00:00Z',
  },
   {
    id: 's3',
    type: ContentType.Quote,
    title: 'Gateway to Reality',
    author: 'Carl Jung',
    preview: '"Who looks outside, dreams; who looks inside, awakes."',
    category: ContentCategory.Spiritual,
    price: 0,
    isPremium: false,
    published: true,
    createdAt: '2024-02-22T12:00:00Z',
  },
  {
    id: 'r1',
    type: ContentType.Research,
    title: 'Neuro-Correlates of Meditative States',
    author: 'MIT Consciousness Lab',
    preview: 'fMRI data on the effects of deep meditation on brainwave patterns and cognitive function.',
    category: ContentCategory.Research,
    price: 129,
    isPremium: true,
    published: true,
    pdfUrl: 'neuro_correlates_meditation.pdf',
    createdAt: '2024-07-18T09:45:00Z',
  },
  {
    id: 'r2',
    type: ContentType.Article,
    title: 'Information Theory of the Soul',
    author: 'Dr. Evelyn Reed',
    preview: 'A theoretical framework for understanding consciousness as a complex informational field.',
    category: ContentCategory.Research,
    price: 59,
    isPremium: true,
    published: false,
    pdfUrl: 'information_theory_soul.pdf',
    createdAt: '2024-07-22T16:00:00Z',
  },
];
